trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- template: '../steps/run-tests.yml'
  parameters:
    envName: 'Sonar'

- script: |
    export PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version);")
    echo "##vso[task.setvariable variable=packageVersion]$PACKAGE_VERSION"
  displayName: 'Extract package version'

- template: templates/yml/any/sonar/run-sonar-cloud-cli-analysis.yml@templates
  parameters:
    projectVersion: $(packageVersion)

